# <span style="color:red"> Lecture 8: Pandas Operations and Data Manipulation </span>

<font size = "4">

Topics we should be familiar up to this point:

- **Object Types**: int, float, str, lists, arrays,<br>
booleans, pandas dataframes


- If/elif/else statements and loops

- Functions (both built-in and user defined)

If there are any of these topics you need help <br>
 understanding, don't be afraid to come to office hours!

<font size = "4">

This lecture:

- We will take a closer look at the `Pandas` library

- A lot of new object types and functions/methods

- We should keep the basic programming ideas listed above in mind

## <span style="color:red"> I. Import Libraries and Read in Files</span>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Read in the car features dataset
carfeatures = pd.read_csv("data/features.csv")

In [ ]:
help(pd.read_csv)
#first, nderstand what it does with the default argument
#then, understand what is returns

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str],
    *,
    sep: str | None | lib.NoDefault = <no_default>,
    delimiter: str | None | lib.NoDefault = None,
    header: int | Sequence[int] | None | Literal['infer'] = 'infer',
    names: Sequence[Hashable] | None | lib.NoDefault = <no_default>,
    index_col: IndexLabel | Literal[False] | None = None,
    usecols: UsecolsArgType = None,
    dtype: DtypeArg | None = None,
    engine: CSVEngine | None = None,
    converters: Mapping[HashableT, Callable] | None = None,
    true_values: list | None = None,
    false_values: list | None = None,
    skipinitialspace: bool = False,
    skiprows: list[int] | int | Callable[[Hashable], bool] | None = None,
    skipfooter: int = 0,
    nrows: int | None = None,
    na_values: Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None = None,
    keep_default_na: bool = True,
    na_filter: bool = True,
    skip_blank_lines: bool = True,
    parse_dates: bool | Sequence[Hashable] | None = None,
    date_format: str | dict[Hashable, str] | None = None,
    dayfirst: bool = False,
    cache_dates: bool = True,
    iterator: bool = False,
    chunksize: int | None = None,
    compression: CompressionOptions = 'infer',
    thousands: str | None = None,
    decimal: str = '.',
    lineterminator: str | None = None,
    quotechar: str = '"',
    quoting: int = 0,
    doublequote: bool = True,
    escapechar: str | None = None,
    comment: str | None = None,
    encoding: str | None = None,
    encoding_errors: str | None = 'strict',
    dialect: str | csv.Dialect | None = None,
    on_bad_lines: str = 'error',
    low_memory: bool = True,
    memory_map: bool = False,
    float_precision: Literal['high', 'legacy', 'round_trip'] | None = None,
    storage_options: StorageOptions | None = None,
    dtype_backend: DtypeBackend | lib.NoDefault = <no_default>
) -> DataFrame | TextFileReader
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{count}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {i}"`` or ``
        "Unnamed: {i}_level_{level}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.

<font size = "4">

Often a good idea to verify the **type** of a variable

In [ ]:
type(carfeatures)

pandas.DataFrame

<font size = "4">

- The type is "pandas.core.frame.DataFrame". 

    - It's a reasonable rule of thumb to only pay attention to the first and last phrases of a datatype like this.

    - So `carfeatures` is a "Pandas DataFrame" object

- You might also want to print the variable itself

In [5]:
print(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [7]:
display(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [9]:
carfeatures

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

<font size = "4">

Or you can view variables by going to the "Jupyter Variables" tab at the top of the notebook. Then click on the icon to the left of `carfeatures` to open it in Data Wrangler.

<font size = "4">

Alternatively, you can also print out just the first 5 rows of `carfeatures`.

In [13]:
print(carfeatures.head()) #head is a function defined in the df; need to use parantheses  

type(carfeatures.head)

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0  18.0          8           307        130    3504          12.0  C-1689780
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824

method

<font size = "4">

Or the first 7 rows:

In [10]:
display(carfeatures.head(7))

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0  18.0          8           307        130    3504          12.0  C-1689780
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824
5  15.0          8           429        198    4341          10.0  F-1689835
6  14.0          8           454        220    4354           9.0  C-1689846

<font size = "4">

**Note:** `.head()` is a *method*. A method is just a function that "belongs" to an object.

## <span style="color:red"> II. Extract column/variable names </span>

<font size = "4">

In Assignment #2, you manually created a list of column names. We saw in Quiz #1 that you can access the column names as follows:

In [ ]:
car_cols = carfeatures.columns #not a function, just a pre-defined variable inside the df 

print(car_cols)
print()
print(type(car_cols))

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'vehicle_id'],
      dtype='str')

<class 'pandas.Index'>

<font size = "4">

- `.columns` is an *attribute*. It is a variable that "belongs" to an object.

- We manually assigned this attribute to a new variable called `car_cols`.

- It is a "Pandas Index" object.

- A Pandas Index also has attributes of its own:

In [19]:
car_colnames = car_cols.values

print(car_colnames)
print(type(car_colnames))

# Is this a list? A Numpy array? Are you checking what objects are, or just coding 
# with reckless abandon?

print(car_colnames[0]) #can axis by indexing
print(type(car_colnames[0])) #all the elements are strings

<ArrowStringArray>
[         'mpg',    'cylinders', 'displacement',   'horsepower',
       'weight', 'acceleration',   'vehicle_id']
Length: 7, dtype: str
<class 'pandas.arrays.ArrowStringArray'>
mpg
<class 'str'>

<font size = "4">

We can even convert `car_colnames` to another type if we want:

In [23]:
col_list = car_colnames.tolist()
print(col_list)
print(type(col_list))

col_numpy = car_colnames.to_numpy()
print(col_numpy)
print(type(col_numpy))

['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'vehicle_id']
<class 'list'>
['mpg' 'cylinders' 'displacement' 'horsepower' 'weight' 'acceleration'
 'vehicle_id']
<class 'numpy.ndarray'>

<font size = "4">

- We could have extracted the names in a single line by "chaining"

In [ ]:
car_colnames = carfeatures.columns.values #df.attribute.attribute; can access all three in one line 
print(car_colnames)

print(type(car_colnames))
print(type(car_colnames[0]))

<ArrowStringArray>
[         'mpg',    'cylinders', 'displacement',   'horsepower',
       'weight', 'acceleration',   'vehicle_id']
Length: 7, dtype: str
<class 'pandas.arrays.ArrowStringArray'>
<class 'str'>

In [ ]:
pd.read_csv("data/features.csv").columns.values.tolist() 
#not necessarily the best way to do it, but possible 

# df -> Pandas Index -> String Array (or convert to list)

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'vehicle_id']

In [24]:
print(type(carfeatures))
carfeatures

<class 'pandas.DataFrame'>

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [25]:
print(type(carfeatures.columns))
carfeatures.columns

<class 'pandas.Index'>

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'vehicle_id'],
      dtype='str')

In [26]:
print(type(carfeatures.columns.values))
carfeatures.columns.values

<class 'pandas.arrays.ArrowStringArray'>

<ArrowStringArray>
[         'mpg',    'cylinders', 'displacement',   'horsepower',
       'weight', 'acceleration',   'vehicle_id']
Length: 7, dtype: str

<font size = "4">

Conversion can be "chained" too:

In [27]:
print(type(carfeatures.columns.values.tolist()))

<class 'list'>

In [28]:
# Just like HW #2, we can use car_colnames to grab columns from the dataset

# manually..
mpg = carfeatures["mpg"]

# using car_colnames
mpg_alt = carfeatures[car_colnames[0]]
print(mpg)
display(mpg_alt)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [ ]:
# Did you check the TYPE ?!
print(type(mpg))

#a dataframe is two-dimensional: multiple variables for each observation (age, weight for each person)
#a series is one-dimension: one variable per observation (age for each person)

<font size = "4">

- A single column of a "Pandas DataFrame" is a "Pandas Series".

- A Pandas Series is a set of 1-dimensional data. Similar to a NumPy array.

- We can also grab multiple columns from a DataFrame:

In [ ]:
list_subsetcols = ["weight","mpg"]
subcols_carfeatures = carfeatures[list_subsetcols] #passing a list of two strings 

print(type(subcols_carfeatures)) #this is not a series because it has two variables 
print()
display(subcols_carfeatures)

<class 'pandas.DataFrame'>

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

In [30]:
# list_subsetcols = ["weight","mpg"] # we created a variable list_subsetcols...
# subcols_carfeatures = carfeatures[list_subsetcols] # ...just to place it within the brackets

# skip the intermediate variable
subcols_carfeatures = carfeatures[ ["weight", "mpg"] ] #inner brackets create the list, outer brackers do the indexing  
print(subcols_carfeatures)

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

In [31]:
print(car_colnames[4]) 
print(car_colnames[0])

weight
mpg

In [32]:
# Use car_colnames plus the indices 4, 0
list_subsetcols = [car_colnames[4], car_colnames[0]]
subcols_carfeatures = carfeatures[list_subsetcols]
print(subcols_carfeatures)

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

In [35]:
subcols_carfeatures = carfeatures[ [car_colnames[4], car_colnames[0]] ]
print(subcols_carfeatures)

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

<font size = "4">

**Exercise**: Extract the weight and acceleration variables

**Exercise**: Extract the displacement, horsepower, and vehicle_id variables

In [38]:
# try yourself (will add the solution later)

subcols_carfeatures_1 = carfeatures[ [ car_colnames[4], car_colnames[5] ] ] #weight, acceleration
print(subcols_carfeatures_1)

subcols_carfeatures_2 = carfeatures[ [ car_colnames[2], car_colnames[3], car_colnames[6] ] ] #displacement, horsepower, id 
print(subcols_carfeatures_2)

     weight  acceleration
0      3504          12.0
1      3693          11.5
2      3436          11.0
3      3433          12.0
4      3449          10.5
..      ...           ...
393    2790          15.6
394    2130          24.6
395    2295          11.6
396    2625          18.6
397    2720          19.4

[398 rows x 2 columns]
     displacement horsepower vehicle_id
0             307        130  C-1689780
1             350        165  B-1689791
2             318        150  P-1689802
3             304        150  A-1689813
4             302        140  F-1689824
..            ...        ...        ...
393           140         86  F-1694103
394            97         52  V-1694114
395           135         84  D-1694125
396           120         79  F-1694136
397           119         82  C-1694147

[398 rows x 3 columns]

## <span style="color:red"> III. Sort by column/variable </span>

<font size = "4">

- We can sort DataFrames according to one of the variables (i.e. one of the columns)

In [ ]:
help(carfeatures.sort_values)

In [ ]:
# sort the data-set by one of the variables
carsorted = carfeatures.sort_values(by = "mpg")
print(carsorted)
print(type(carsorted))

In [ ]:
# above we went from lowest mileage to highest mileage (ascending order)
# 
# To reverse the order, pass in the argument ascending = False 

carsorted = carfeatures.sort_values(by = "mpg", ascending = False)
print(carsorted)

## <span style="color:red"> IV. Subsetting by row/column position </span>

<font size = "4">

- In assignment #5, we saw how to use the `.loc` attribute to grab the value of a variable from a given row. We'll come back to that method in a later lecture.

- In addition, each DataFrame has an "iloc" attribute. This stands for "integer-location based indexing".

- **Important Note:** `.iloc` is an attribute, not a method! You use square brackets `[]` not parentheses!

In [ ]:
print(carfeatures)

In [ ]:
# Above, see that car 0 has 18.0 mpg
# The value "18.0" is in the first row, and corresponds to the first column
# (the index column on the left is NOT considered a column/variable)

# Since Python starts counting from zero, this is in row 0 column 0

car0_mpg = carfeatures.iloc[0,0]
print(car0_mpg)

In [ ]:
# Above, see that car 3 has weight of 3433
# Counting from zero, the value "3433" is in
# row 3, column
# The value "3433" is in row 3, column 4

car3_weight = carfeatures.iloc[3, 4]
print(car3_weight)

In [ ]:
# Let's grab ALL the features for car 0 (mpg, cylinders, displacement, ..., vehicle_id)

# So we want all the entries along row zero. 
# Use a ":" (colon) for the column index to grab ALL the columns

car0_features = carfeatures.iloc[0,:]
print(car0_features)
print()
print(type(car0_features))

In [ ]:
# Grab all columns of car 3
car3_features = carfeatures.iloc[3,:]
print(car3_features)

In [ ]:
print(carfeatures)

In [ ]:
# Column 0 corresponds to "mpg" (the index column on the far left doesn't count)

# Grab the entire column 0, which means grabbing ALL the rows

car_mpg = carfeatures.iloc[:, 0]
print(car_mpg)

In [ ]:
# horsepower is column 3
# grab ALL rows of column 3

car_horsepower = carfeatures.iloc[:, 3]
car_horsepower

In [ ]:
# Grab all features for cars 0, 4, 396 (so rows 0, 4, 396)

cargroup_features = carfeatures.iloc[[0, 4, 396],:]
print(cargroup_features)
print(type(cargroup_features))

In [ ]:
# Grab all features for cars 0, 4, 396 (so rows 0, 4, 396)

group_rows = [0, 4, 396]
cargroup_features = carfeatures.iloc[ group_rows, : ]
print(cargroup_features)

In [ ]:
# Grab mpg, weight, vehicle_id for ALL cars (columns 0, 4, 6)

subfeatures = carfeatures.iloc[ : , [0, 4, 6] ]
print(subfeatures)

In [ ]:
# Grab mpg, weight, vehicle_id for ALL cars (columns 0, 4, 6)

sub_cols = [0, 4, 6]
subfeatures = carfeatures.iloc[ : , sub_cols]
print(subfeatures)

In [ ]:
# Grab mpg, weight, vehicle_id for cars 0, 4, 396
# So we need rows 0, 4, 396
# and columns 0, 4, 6

subdata = carfeatures.iloc[ [0, 4, 396], [0, 4, 6] ]
print(subdata)

### Subsetting blocks of rows

In [ ]:
# let's grab all features for the first 5 cars
# (rows 0, 1, 2, 3, 4)

first_5_cars = carfeatures.iloc[ :5, :]
print(first_5_cars)

In [ ]:
# let's grab all features for the first 5 cars
# (rows 0, 1, 2, 3, 4)

# we start with row 0
# the first row we *exclude* is row 5
first_5_cars = carfeatures.iloc[ 0:5, :]
print(first_5_cars)

In [ ]:
# if we shift the indices by 1
# (change 0:5 --> 1:6)
# Then we will grab rows (1,2,3,4,5)

cars_1_thru_5 = carfeatures.iloc[ 1:6, :]

# we start with row 1
# the first row we *exclude* is row 6

print(cars_1_thru_5)

In [ ]:
# grab rows 211-219 (so 220 is the first one we exclude)
carfeatures.iloc[ 211:220 , :]

In [ ]:
print(carfeatures)

In [ ]:
# grab last 3 rows (rows 395, 396, and 397)
carfeatures.iloc[ -3: , :]

In [ ]:
# grab 3rd from last row and 2nd from last row (exclude last row)
carfeatures.iloc[ -3:-1 , :]

<font size = "4">

Works similarly for blocks of columns, or blocks of both rows and columns

**Exercise:** Extract the columns corresponding to displacement, horsepower, and weight for all cars using ``.iloc``. The column indices should be of the form ``start:stop`` for appropriate integers ``start`` and ``stop``

**Exercise:** Extract the weight, acceleration, and vehicle_id information for cars 28, 29, 30, 31, 32 using ":" for both row and column indices

In [ ]:
## your answer here

<font size = "4">

**Exercise:** Create a dataset ``car_ascendingweight`` which sorts the cars from lowest to highest weight. Then extract the subset of the data corresponding to the 5 cars with the lowest weight (all their features, not just their weight)

In [ ]:
# your answer here

## <span style="color:red"> V. Adding Variables </span>

<font size = "4">

- Sometimes we don't want to simply read in a dataset, but **manipulate** the data in some way
- One of the most simple data manipulations is to add new variables/columns

We'll demonstrate with a data-set of the heights and weights of a sample of people. The dataset is from the Statistics Online Computational Resource (SOCR)

In [ ]:
df_ht_wt = pd.read_csv("data/SOCR-HeightWeight.csv")
print(df_ht_wt.columns.values)
print()
print(df_ht_wt)

<font size = "4">

- The dataset contains the height and weight of people measured in inches and pounds, respectively. 
- Using these two variables, we can calculate a new variable: the BMI (Body Mass Index) of each person.
- The formula for BMI is given by the formula:
$$\textrm{BMI } = \frac{\textrm{weight in kg}}{\left(\textrm{height in meters}\right)^2}$$

In [ ]:
# Grab height and weight and convert to correct units

def pounds_to_kg(wt):
    return wt*0.45359237

def inches_to_meters(ht):
    ht_mm = ht*25.4
    return ht_mm*1e-3

ht_inch = df_ht_wt["Height(Inches)"]
wt_lbs = df_ht_wt["Weight(Pounds)"]

ht_meters = ht_inch.apply(inches_to_meters)
ht_meters.name = "Height(Meters)"
wt_kg = wt_lbs.apply(pounds_to_kg)
wt_kg.name = "Weight(Kilograms)"

<font size = "4">

**Exercise**: Repeat the operations in the last cell, but grab ``ht_inch`` and ``wt_lbs`` using ``.iloc`` instead of the column names

In [ ]:
# your code here

<font size = "4">

Now, calculate BMI using these two variables and add to the dataset

In [ ]:
df_ht_wt.head()

In [ ]:
# Math operations on Pandas series work very similarly to Numpy arrays

BMI = wt_kg/ht_meters**2

# assign the new Pandas series to a new column of the dataframe
df_ht_wt["BMI"] = BMI

In [ ]:
df_ht_wt.head()

<font size = "4">

**Application:** Random Assignment

- Random assignment is an experimental technique for dividing a data set into groups using randomization
- Typically a data point has an equal probability of being placed in each group (but not necessary)
- Let's say we want to divide up the height/weight dataset into 4 groups. We can use Numpy.random to assign each person the number 1, 2, 3, or 4

In [ ]:
# get size of data-set
num_rows, num_cols = df_ht_wt.shape

# randomly generate a number (1,2,3, or 4) for each person in the dataset
group_no = np.random.choice([1, 2, 3, 4], size = num_rows)

df_ht_wt["GroupID"] = group_no

In [ ]:
df_ht_wt.head()

## <span style="color:red"> VI. Filtering Dataframes Based on Logical Expressions </span>

<font size = "4">

(i) Filtering using ```pandas.query()``` 

```python
data.query("logical expression")
```

In [ ]:
high_mileagecars = carfeatures.query("mpg >= 25")
print(high_mileagecars)

In [ ]:
group_4 = df_ht_wt.query("GroupID == 4")
print(group_4)

In [ ]:
# Use "and" / "or" for logical operations on queries

car_subset = carfeatures.query("(acceleration >= 12) and (acceleration < 18)")
print(car_subset)

<font size = "4">

(ii) Expressions with colnames + global variables (@)

In [ ]:
# You can invoke global variables into the query by using @variablename
# If you don't include @, then Python will try to look for a column with 
# that name.

threshold = 25
high_mileagecars = carfeatures.query("mpg >= @threshold")
print(high_mileagecars)

In [ ]:
lb = 12
ub = 18

car_subset = carfeatures.query("(acceleration >= @lb) and (acceleration < @ub)")
print(car_subset)

<font size = "4">

Handling white space on a computer can be annoying in certain situations, as we will see here:

In [ ]:
# same data set, but column/variable 0 is "miles per gallon" instead of "mpg"

new_dset = pd.read_csv("data/features-bad-spacing.csv")
print(new_dset)

In [ ]:
data_threshold_horsepower = new_dset.query("miles per gallon >= 20")

<font size = "4">

Pretty scary looking error message...basically, it doesn't like the space (variable names can't have spaces in Python)

We've seen the double quote (") and the single quote (')

To the left of your 1 key is the backtick/grave accent (`). Need to use this

In [ ]:
# next line causes error
# data_threshold_horsepower = new_dset.query("miles per gallon >= 20")

# this next line is fine
data_threshold_horsepower = new_dset.query("`miles per gallon` >= 20")
print(data_threshold_horsepower)

<font size = "4">

**Exercise:** Subset the data, gathering all cars with exactly 8 cylinders and mpg $\ge$ 25.

In [ ]:
# Your solution here

## <span style="color:red"> VII. Application: Visualizing Subsets of the Data </span>

<font size = "4">

List of unique categories

In [ ]:
# Use pd.unique() to extract a numpy array with the unique elements in that column

array_unique_cylinders = pd.unique(carfeatures["cylinders"])
print(array_unique_cylinders)
print(type(array_unique_cylinders))

<font size = "4">

Compute two overlapping plots

In [ ]:
# If we call plt.scatter() twice to display two plots
# To display all plots simultaneously we include plt.show() at the very end.
# The idea is that the graphs are stacked on top of each other

df_8 = carfeatures.query("cylinders == 8")
df_4 = carfeatures.query("cylinders == 4")

plt.scatter(x = df_8["weight"],y = df_8["acceleration"])
plt.scatter(x = df_4["weight"],y = df_4["acceleration"])
plt.legend(labels = ["8","4"],
           title  = "Cylinders")

plt.xlabel("Weight")
plt.ylabel("Acceleration")
plt.show()

# Note: If we put plt.show() in between the plots, then the results will
# be shown on separate graphs instead.

<font size = "4">

Compute plots by all categories

In [ ]:
# Compute number of unique categories
list_unique_cylinders = pd.unique(carfeatures["cylinders"])

# Use a for loop to plot a scatter plot between "weight" and "acceleration"
# for each category. Each plot  will have a different color

for category in list_unique_cylinders:
    df   = carfeatures.query("cylinders == @category")
    plt.scatter(x = df["weight"], y = df["acceleration"])
    
# Add labels and a legends    
plt.xlabel("Weight")
plt.ylabel("Acceleration")
plt.legend(labels = list_unique_cylinders,
           title  = "Cylinders")
plt.show()

<font size="4">

**Exercise:** Compute a histogram of "mpg" by cylinder count for cars with 4, 6, and 8 cylinders.Here is what it might look like (using a fake dataset):

<img src="data/fake_histogram.png" alt="drawing" width="400"/>


You can make the histograms transparent by adjusting ```alpha``` in

```python
    plt.hist(x = ..., alpha = 0.5)
```

In [ ]:
# your code here